remote_theme: galette/theme-ghpages
title: Galette Legal Notices
description: Plugin to manage legal notices
author: Guillaume AGNIERAY
maintainer: community
plugin:
  name: LegalNotices
  archive: galette-plugin-legal-notices
  min_galette: "1.3.0"
defaults:
  - scope: {path: ""}
    values: {layout: default}
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
