--
-- This file is part of Galette Legal Notices plugin (https://galette-community.github.io/plugin-legalnotices).
-- SPDX-FileCopyrightText: Copyright © 2025-2026 The Galette Team
-- SPDX-License-Identifier: GPL-3.0-or-later
--

DROP TABLE IF EXISTS galette_legalnotices_settings CASCADE;
CREATE TABLE galette_legalnotices_settings (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  name character varying(100) NOT NULL,
  value character varying(255) NOT NULL,
  PRIMARY KEY (id)
);
CREATE UNIQUE INDEX galette_legalnotices_settings_name_idx ON galette_legalnotices_settings (name);

--
-- Table structure for table `galette_legalnotices_pages`
--
DROP TABLE IF EXISTS galette_legalnotices_pages CASCADE;
CREATE TABLE galette_legalnotices_pages (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  name character varying(20) NOT NULL,
  body text NOT NULL,
  url character varying(255) NOT NULL,
  lang character varying(16) NOT NULL,
  label character varying(255) NOT NULL,
  last_update timestamp NOT NULL,
  PRIMARY KEY (id)
);
CREATE UNIQUE INDEX galette_legalnotices_pages_localizedpage_idx ON galette_legalnotices_pages (name, lang);
